version: "3"
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        ports:
          - "5432:5432"
        volumes:
          - /data/postgres:/data/postgres
        env_file:
          - docker.env
        networks:
          - postgres
    pgadmin:
        links:
          - postgres:postgres
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
          - "8080:80"
        volumes:
          - /data/pgadmin:/root/.pgadmin
        env_file:
          - docker.env
        networks:
          - postgres
    api:
        build: .
        ports:
          - 3000:3000
        depends_on:
          - postgres
        command: npm run debug
        links:
          - postgres:postgres
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
networks:
    postgres:
        driver: bridge
